CREATE DATABASE MiBaseDeDatos; 
SET DATABASE MiBaseDeDatos;
CREATE TABLE Usuarios (ID INTEGER NOT NULL, Nombre VARCHAR(100) NOT NULL, Edad INTEGER NOT NULL, FechaRegistro DATETIME NULL);
INSERT INTO Usuarios VALUES (1, 'Juan Pérez', 30, '2024-09-24 10:30:00');
SELECT * FROM Usuarios;


